#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt install firefox 
sudo apt install vim
sudo apt install python-pip
sudo apt install python3-pip
pip install virtualenv
pip3 install virtualenv
sudo 'alias Venv="source Venv/bin/activate"' >> /home/eric/.bashrc
sudo 'alias o="xdg-open"' >> /home/eric/.bashrc

echo "Installing Docker!"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"
sudo apt-get update
sudo apt-get install docker-ce
echo "Docker installed Successfully!"

echo "Installing Java 11!"
sudo add-apt-repository ppa:linuxuprising/java
sudo apt-get update
sudo apt-get install oracle-java11-installer
sudo apt-get install oracle-java11-set-default
echo "Java 11 has been Installed!"

echo "Installing Eclipse for Java !"
curl -o /home/eric/Downloads/eclipse-installer-delete-Me.tar.gz ftp.fau.de/eclipse/oomph/epp/2018-12/R/eclipse-inst-linux64.tar.gz
tar xvzf /home/eric/Downloads/eclipse-installer-delete-Me.tar.gz
sudo rm /home/eric/Downloads/eclipse-installer-delete-Me.tar.gz
echo ""
echo "PLEASE CHANGE DEFAULT DIRECTORY TO BE IN /home/eric/ NOT /root/ !!!!"
echo ""
sudo /home/eric/Downloads/eclipse-installer/./eclipse-inst
sudo 'alias eclipse="sudo /home/eric/eclipse/./eclipse"' >> /home/eric/.bashrc
echo "Eclipse Has been Installed!"

echo "Installing R and R studio"
sudo apt -y install r-base
sudo apt install gdebi-core
curl -o /home/eric/Downloads/r-studio-DeleteMe.deb https://download1.rstudio.org/rstudio-xenial-1.1.463-amd64.deb
sudo gdebi /home/eric/Downloads/r-studio-DeleteMe.deb
rm -rf /home/eric/Downloads/r-studio-DeleteMe.deb
echo "R studio installed"
